### ISSUE TITLE
Check Important Keynote.app Preferences

### ISSUE THREAD

**Issue by agnat** [artcom/ac_presentation_shell#28]
ACShell should issue a warning if important keynote preferences have the wrong setting. Examples are:
-   Back up previous version (This pollutes the library and should be off)
-   Save new documents as packages (This helps rsync to do its job and should be on)

**Comment by jkrumow** [comment]
Both settings are obsolete right now. First one because of time machine, second one because newer Keynote versions save presentations as files.
