### ISSUE TITLE
Add optional faster SSH cipher

### ISSUE THREAD

**Issue by kaazoo** [artcom/ac_presentation_shell#35]
When executing rsync a faster SSH cipher like 'arcfour' could be used. This decreases transport security but can lead to heavy transfer speedups. Might be nice for inhouse transfers.

Normal rsync is executed like this:

```
rsync source:/path destination:/path
```

Rsync with extra SSH arguments is excuted like this:

```
rsync -e "ssh -c arcfour" source:/path destination:/path
```

In https://github.com/artcom/ac_presentation_shell/blob/master/Classes/RsyncTask.m#L77 the array 'taskArgs' holds all arguments for rsync. The optional argument could be added here.

**Comment by jkrumow** [comment]
Wont be implemented because:

- security should not be weakened
